routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

use App\ListRole;
use App\Penelitian;
use App\Pengabdian;
use App\RoleUser;
use App\SkemaPenelitian;
use App\SkemaPengabdian;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Using Closure based composers...
View::composer(['*'], function ($view) {
	if (isset(Auth::user()->id)) {
		$role = RoleUser::select('roles.description as description')
							->join('roles', 'role_user.role_id', 'roles.id')
							->firstWhere('role_user.user_id', Auth::user()->id);

		$roles = ListRole::select('list_roles.role_id as role_id', 'roles.description as description')
							->join('roles', 'list_roles.role_id', 'roles.id')
							->where('list_roles.user_id', Auth::user()->id)
							->get();
							
		$username = User::join('user_data', 'users.username', 'user_data.nidn')
							->select('user_data.nama', 'user_data.nidn')
							->firstWhere('users.id', Auth::user()->id);

		$rolecount = $roles->count();

        $skemaPenelitian = SkemaPenelitian::getSkemaByNIDN(Auth::user()->username);
        $skemaPengabdian = SkemaPengabdian::getSkemaByNIDN(Auth::user()->username);
										
		$view->with('skemaPenelitian', $skemaPenelitian);
		$view->with('skemaPengabdian', $skemaPengabdian);
		$view->with('role', $role);
		$view->with('roles', $roles);
		$view->with('rolecount', $rolecount);
		$view->with('username', $username);
	}
});

Route::get('tes', 'HomeController@test');

Route::get('/install','InstallController@install');
Auth::routes();
//testing upload read doc
Route::get('/doc','HomeController@docTest');
Route::post('/doc','HomeController@docProses');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/author', 'HomeController@author')->name('author');
Route::get('/penelitian/{id}', 'HomeController@firstPenelitian');
Route::get('/pengabdian/{id}', 'HomeController@firstPengabdian');
Route::get('/author', 'HomeController@author')->name('author');

Auth::routes();
Route::resource('/profil', 'ProfilController', [
	'only' => ['index', 'update']
]);
Route::get('/profil/edit', 'ProfilController@edit')->name('profil.edit');
Route::get('/skema/penelitian/{id}', 'HomeController@skemaPenelitian');
Route::get('/skema/pengabdian/{id}', 'HomeController@skemaPengabdian');


/*Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');
*/

Route::get('publications', 'Admin\GoogleScholarController@publications');
Route::get('latest-publication', 'Admin\GoogleScholarController@publication');
Route::get('statistics', 'Admin\GoogleScholarController@statistics');

Route::get('kepala-prodi', 'HomeController@getKepalaProdi')->name('getKepalaProdi');
Route::get('kepala-prodi/{id}', 'HomeController@firstKepalaProdi')->name('firstKepalaProdi');
Route::post('roles', 'HomeController@updateRole')->name('role_update');

Route::group(['prefix' => 'admin'], function()
{
	// semua url /admin/.. digroup sini
	//Route::get('/tes/{nidn}','Admin\PenelitianController@tes');
	Route::get('/', 'Admin\AdminController@index');

	Route::resource('penilaian', 'Admin\PenilaianController', ['only' => 'index'])->names(['index' => 'adminPenilaian.index']);

	Route::group(['prefix' => 'reviewer'], function () {
		Route::resource('/', 'Admin\ReviewerController', [
			'only' => ['index', 'store']
		])->names([
			'index' => 'adminReviewer.index',
			'store' => 'adminReviewer.store'
		]);
		Route::get('generate-penelitian', 'Admin\ReviewerController@generateReviewerPenelitian')->name('adminReviewer.generatePenelitian');
		Route::get('generate-pengabdian', 'Admin\ReviewerController@generateReviewerPengabdian')->name('adminReviewer.generatePengabdian');
	});

	Route::group(['prefix' => 'skema'], function()
	{
		Route::resource('/', 'Admin\SkemaController', ['only' => 'index'])->names(['index' => 'skema.index']);
		Route::get('/data-penelitian/{id}', 'Admin\AdminController@getskemapenelitian');
		Route::get('/data-pengabdian/{id}', 'Admin\AdminController@getskemapengabdian');
		Route::resource('/penelitian', 'Admin\SkemaPenelitianController', [
			'except' => 'index'
		])->names([
			'create' => 'skemapenelitian.create',
			'store' => 'skemapenelitian.store',
			'show' => 'skemapenelitian.show',
			'edit' => 'skemapenelitian.edit',
			'update' => 'skemapenelitian.update',
			'destroy' => 'skemapenelitian.destroy'
		]);
		Route::resource('/pengabdian', 'Admin\SkemaPengabdianController', [
			'except' => 'index'
		])->names([
			'create' => 'skemapengabdian.create',
			'store' => 'skemapengabdian.store',
			'show' => 'skemapengabdian.show',
			'edit' => 'skemapengabdian.edit',
			'update' => 'skemapengabdian.update',
			'destroy' => 'skemapengabdian.destroy'
		]);
	});

	Route::group(['prefix' => 'user'], function()
	{
		Route::get('/', 'Admin\UserController@index')->name('user.index');
		Route::post('/update-password', 'Admin\UserController@updatepassword')->name('admin.updatepassword');
		Route::post('/update-user', 'Admin\UserController@updateuser')->name('admin.updateuser');
	});

	Route::get('/data-dosen/{id}', 'Admin\AdminController@getDosen');
	Route::resource('/dosen', 'Admin\DosenController');
	Route::get('/reset-password/{id}', 'Admin\UserController@resetPassword')->name('admin.reset_password');
	Route::get('/role-user/{id}', 'Admin\AdminController@getRole');
	Route::group(['prefix' => 'penelitian'], function()
		{
			Route::get('/usulan','Admin\PenelitianController@getAllUsulan');
		}
	);
	Route::group(['prefix' => 'pengabdian'], function()
		{
			Route::get('/usulan','Admin\PengabdianController@getAllUsulan');
		}
	);
	
	Route::get('/data-usulan/penelitian/{id}', 'Admin\AdminController@getUsulanPenelitian');
	Route::get('/data-usulan/pengabdian/{id}', 'Admin\AdminController@getUsulanPengabdian');
	Route::get('/data-penilaian/{id}', 'Admin\PenilaianController@firstPenelitian');
	Route::get('/approver', function() {
    return view('admin.approver');
	});
});

Route::group(['prefix' => 'dosen'], function(){
	// semua url /dosen/.. digroup sini

	Route::get('/','Dosen\DosenController@index');
	Route::resource('/tanggungan', 'Dosen\TanggunganController');
	Route::get('/sinta', 'Dosen\DosenController@sinta')->name('dosen.sinta');
	Route::resource('/usulan', 'Dosen\UsulanController', [
		'only' => ['index', 'create', 'store', 'show', 'update']
	]);
	Route::resource('/pengabdian', 'Dosen\UsulanPengabdianController', [
		'only' => ['index', 'create', 'store', 'show', 'update']
	]);
});

Route::group(['prefix' => 'pimpinan'], function()
{
	// semua url /pimpinan/.. digroup sini

	Route::view('/', 'home.pimpinan');
	Route::get('/approver', function() {
    return view('pimpinan.approver');
	});

	Route::resource('penilaian', 'Admin\PenilaianController', ['only' => 'index'])->names(['index' => 'pimpinanPenilaian.index']);

	Route::group(['prefix' => 'reviewer'], function () {
		Route::resource('/', 'Admin\ReviewerController', [
			'only' => ['index', 'store']
		])->names([
			'index' => 'pimpinanReviewer.index',
			'store' => 'pimpinanReviewer.store'
		]);
		Route::get('generate-penelitian', 'Admin\ReviewerController@generateReviewerPenelitian')->name('pimpinanReviewer.generatePenelitian');
		Route::get('generate-pengabdian', 'Admin\ReviewerController@generateReviewerPengabdian')->name('pimpinanReviewer.generatePengabdian');
	});
});

Route::group(['prefix' => 'penelitian'], function()
{
	// semua url /penelitian/.. digroup sini

	Route::view('/', 'home.penelitian');
	Route::get('/pembagian-reviewer', function() {
    return view('penelitian.pembagian-reviewer');
	});
});

Route::group(['prefix' => 'pengabdian'], function()
{
	// semua url /pengabdian/.. digroup sini

	Route::view('/', 'home.pengabdian');
	Route::get('/pembagian-reviewer', function() {
    return view('pengabdian.pembagian-reviewer');
	});
});

Route::group(['prefix' => 'reviewer'], function()
{
	// semua url /reviewer/.. digroup sini

	Route::get('/', 'Reviewer\ReviewerController@index')->name('reviewerHome.index');
	Route::resource('/review', 'Reviewer\ReviewController', [
		'only' => ['index', 'store']
	])->names([
		'index' => 'reviewerReview.index', 'store' => 'reviewerReview.store'
	]);
	Route::get('/tes', function() {
    return view('reviewer.review');
	});
});

app/Http/Controllers/Admin/DosenController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Dosen;
use App\Role;
use App\ListRole;
use App\User;
use App\UserRole;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use App\JabatanAkademik;

class DosenController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Untuk mengambil Data Role sesuai User
        $dosen = Dosen::all();

        return view('admin.dosen', compact('dosen'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jabatan_akademik = JabatanAkademik::get();

        return view('admin.dosen-create', compact('jabatan_akademik'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nidn' => 'numeric',
            'nama' => 'required',
            'alamat' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required|date',
            'ktp' => 'required|numeric',
            'telepon' => 'required|numeric',
            'hp' => 'required|numeric',
            'email' => 'required|email',
            'website_personal' => 'required',
            'jabatan_fungsional' => 'required',
            'sinta_id' => 'required',
            'google_scholar' => 'required'
        ]);
        
        $ceknidn = Dosen::where('nidn', $request->get('nidn'))->first();
        if (isset($ceknidn->nidn)) {
            return back()->with('error', 'Data dosen telah terdaftar');
        } else {
            $nidn = $request->get('nidn');
            $nama = $request->get('nama');
            $alamat = $request->get('alamat');
            $tempat_lahir = $request->get('tempat_lahir');
            $tanggal_lahir = $request->get('tanggal_lahir');
            $ktp = $request->get('ktp');
            $telepon = $request->get('telepon');
            $hp = $request->get('hp');
            $email = $request->get('email');
            $website_personal = $request->get('website_personal');
            $jabatan_fungsional = $request->get('jabatan_fungsional');
            $sinta_id = $request->get('sinta_id');
            $google_scholar = $request->get('google_scholar');
            $status = 1;
            
            if ($request->get('status') == null) {
                $status = 2;
            }
    
            $user_data = Dosen::storeDosen($nidn, $nama, $alamat, $tempat_lahir, $tanggal_lahir, $ktp, $telepon, $hp, $email, $website_personal, $jabatan_fungsional, $sinta_id, $google_scholar, $status);
            $user = User::storeUser($nidn);
            $list_role = ListRole::storeListRole();
    
            return redirect()->route('dosen.index')->with('success', 'Data dosen telah ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dosen = Dosen::findOrFail($id);
        $jabatan_akademik = JabatanAkademik::get();

        return view('admin.dosen-edit', compact('dosen', 'jabatan_akademik'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function importExcel()
    {
        $this->validate($request, [
            'select_file'   => 'required|mimes:xls,xlsx'
        ]);
        
        Excel::import(new DosenImport, request()->file('select_file'));

        return redirect('/')->with('success', 'Data dosen berhasil ditambahkan');
    }
}

app/Http/Controllers/Dosen/DosenController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\ListRole;
use App\Dosen;

class DosenController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:dosen');
    }

    public function index()
    {
        $dosen = Dosen::findOrFail(Auth::user()->id);
        return view('home.dosen', compact('dosen'));
    }
    
    public function sinta()
    {
        $dosen = Dosen::findOrFail(Auth::user()->id);
        return view('dosen.sinta', compact('dosen'));
    }
}

app/Http/Controllers/Dosen/SintaController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SintaController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:dosen');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dosen.sinta');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dosen/TanggunganController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TanggunganController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:dosen');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dosen.tanggungan');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dosen/profil-edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Ubah Profil</h1>
@stop

@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/fontawesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">
@endsection

@section('content')
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Ubah Profil</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{{ route('profil.update', $dosen->id) }}">
              @csrf
              @method('PATCH')
              <div class="card-body">
                @if ($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                          <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                  </div><br />
                @endif
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="ktp">No. KTP</label>
                      <input type="number" class="form-control" id="ktp" name="ktp" placeholder="Masukkan No. NIK KTP" value="{{ $dosen->ktp }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <!-- textarea -->
                    <div class="form-group">
                      <label>Alamat</label>
                      <textarea class="form-control" rows="4" name="alamat" placeholder="Masukkan Alamat">{{ $dosen->alamat }}</textarea>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="telepon">No. Telepon</label>
                      <input type="number" class="form-control" id="telepon" name="telepon" placeholder="Masukkan No. Telepon" value="{{ $dosen->telepon }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="hp">No. HP</label>
                      <input type="number" class="form-control" id="hp" name="hp" placeholder="Masukkan No. HP" value="{{ $dosen->hp }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="email">Email</label>
                      <input type="email" class="form-control" id="email" name="email" placeholder="Masukkan Email" value="{{ $dosen->email }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="website_personal">Alamat Website Pribadi</label>
                      <input type="text" class="form-control" id="website_personal" name="website_personal" placeholder="Masukkan Alamat Website Pribadi" value="{{ $dosen->website_personal }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="nidn">NIDN</label>
                      <input type="number" class="form-control" id="nidn" name="nidn" placeholder="Masukkan NIDN" value="{{ $dosen->nidn }}">
                    </div>
                  </div>
                  <div class="col-md-6">                    
                    <div class="form-group">
                      <label>Jabatan Fungsional</label>
                      <select class="form-control" id="jabatan_fungsional" name="jabatan_fungsional" required>
                        <option value="" hidden>--Pilih Jabatan Fungsional</option>
                        @foreach ($jabatan_akademik as $item)
                            <option value="{{$item->id}}"
                              @if ($dosen->jabatan_fungsional == $item->id)
                                selected  
                              @endif
                            >{{$item->nama}}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">FOTO PROFIL</label>
                      <div class="input-group">
                        <div class="custom-file">
                          <input type="file" class="custom-file-input" id="exampleInputFile">
                          <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
        </div>
        <!--/.col (left) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@stop

@section('js')
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('vendor/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
@endsection

resources/views/dosen/profil.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Profil Pengguna</h1>
@stop

@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/fontawesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">
@endsection

@section('content')
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Informasi Pribadi</h3>

              <div class="card-tools">
                <a href="{{ route('profil.edit') }}" class="btn btn-sm btn-success">Ubah Profil</a>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              @if(session()->get('success'))
                <div class ="alert alert-success">
                  {{ session()->get('success') }}  
                </div><br />
              @endif
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <p class="text-primary font-weight-bold mb-1">No KTP:</p>
                    <p>{{ $dosen->ktp }}</p>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <p class="text-primary font-weight-bold mb-1">Alamat:</p>
                    <p>{{ $dosen->alamat }}</p>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <p class="text-primary font-weight-bold mb-1">No Telepon:</p>
                    <p>{{ $dosen->telepon }}</p>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <p class="text-primary font-weight-bold mb-1">No Handphone:</p>
                    <p>{{ $dosen->hp }}</p>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <p class="text-primary font-weight-bold mb-1">Email:</p>
                    <p>{{ $dosen->email }}</p>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <p class="text-primary font-weight-bold mb-1">Website Personal:</p>
                    <p>{{ $dosen->website_personal }}</p>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <p class="text-primary font-weight-bold mb-1">NIDN:</p>
                    <p>{{ $dosen->nidn }}</p>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <p class="text-primary font-weight-bold mb-1">Jabatan Akademik:</p>
                    <p>{{ $jabatan_akademik->nama }}</p>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!--/.col (left) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@stop

@section('js')
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
@endsection

resources/views/dosen/tanggungan.blade.php
@extends('adminlte::page')

@section('usulan-open')
    menu-open
@endsection

@section('usulan-active')
    active
@endsection

@section('tanggungan-active')
    active
@endsection

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Tanggungan</h1>
@stop

@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/fontawesome.min.css') }}">
@endsection

@section('content')
  <!-- Main content -->
  <section class="content">
    <p class="text-secondary">Daftar Tanggungan yang masih berlaku</p>
    <div class ="alert alert-success">
      Pemberitahuan! Tidak ada tanggungan  
    </div><br />
    <!-- /.alert -->
  </section>
  <!-- /.content -->
@stop

@section('js')
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
@endsection

resources/views/dosen/usulan-create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Tahapan Usulan</h1>
@stop

@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/fontawesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">
@endsection

@section('content')
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- column -->
        <div class="col">
          <!-- general form elements -->
          <div class="card">
            <div class="card-header">
              <div class="card-title">
                @if ($form == 1)
                  Step 1 - Identitas Usulan
                @endif
                @if ($form == 2)
                  Step 2 - Atribut Usulan
                @endif
                @if ($form == 3)
                  Step 3 - Anggota Peneliti
                @endif
                @if ($form == 4)
                  Step 4 - Biaya Usulan
                @endif
                @if ($form == 5)
                  Step 5 - Isian Pengesahan 
                @endif
              </div>
            </div>
            <!-- form start -->
            @for ($i = 1; $i < 6; $i++)
                @if ($form == $i)
                    @include('dosen.usulan.form' . $i)
                @endif
            @endfor
            <!-- /.form end -->
          </div>
          <!-- /.card -->
        </div>
        <!--/.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@stop

@section('js')
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
@endsection