routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

use App\ListRole;
use App\Penelitian;
use App\Pengabdian;
use App\RoleUser;
use App\SkemaPenelitian;
use App\SkemaPengabdian;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Using Closure based composers...
View::composer(['*'], function ($view) {
	if (isset(Auth::user()->id)) {
		$role = RoleUser::select('roles.description as description')
							->join('roles', 'role_user.role_id', 'roles.id')
							->firstWhere('role_user.user_id', Auth::user()->id);

		$roles = ListRole::select('list_roles.role_id as role_id', 'roles.description as description')
							->join('roles', 'list_roles.role_id', 'roles.id')
							->where('list_roles.user_id', Auth::user()->id)
							->get();
							
		$username = User::join('user_data', 'users.username', 'user_data.nidn')
							->select('user_data.nama', 'user_data.nidn')
							->firstWhere('users.id', Auth::user()->id);

		$rolecount = $roles->count();

        $skemaPenelitian = SkemaPenelitian::getSkemaByNIDN(Auth::user()->username);
        $skemaPengabdian = SkemaPengabdian::getSkemaByNIDN(Auth::user()->username);
										
		$view->with('skemaPenelitian', $skemaPenelitian);
		$view->with('skemaPengabdian', $skemaPengabdian);
		$view->with('role', $role);
		$view->with('roles', $roles);
		$view->with('rolecount', $rolecount);
		$view->with('username', $username);
	}
});

Route::get('tes', 'HomeController@test');

Route::get('/install','InstallController@install');
Auth::routes();
//testing upload read doc
Route::get('/doc','HomeController@docTest');
Route::post('/doc','HomeController@docProses');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/author', 'HomeController@author')->name('author');
Route::get('/penelitian/{id}', 'HomeController@firstPenelitian');
Route::get('/pengabdian/{id}', 'HomeController@firstPengabdian');
Route::get('/author', 'HomeController@author')->name('author');

Auth::routes();
Route::resource('/profil', 'ProfilController', [
	'only' => ['index', 'update']
]);
Route::get('/profil/edit', 'ProfilController@edit')->name('profil.edit');
Route::get('/skema/penelitian/{id}', 'HomeController@skemaPenelitian');
Route::get('/skema/pengabdian/{id}', 'HomeController@skemaPengabdian');


/*Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');
*/

Route::get('publications', 'Admin\GoogleScholarController@publications');
Route::get('latest-publication', 'Admin\GoogleScholarController@publication');
Route::get('statistics', 'Admin\GoogleScholarController@statistics');

Route::get('kepala-prodi', 'HomeController@getKepalaProdi')->name('getKepalaProdi');
Route::get('kepala-prodi/{id}', 'HomeController@firstKepalaProdi')->name('firstKepalaProdi');
Route::post('roles', 'HomeController@updateRole')->name('role_update');

Route::group(['prefix' => 'admin'], function()
{
	// semua url /admin/.. digroup sini
	//Route::get('/tes/{nidn}','Admin\PenelitianController@tes');
	Route::get('/', 'Admin\AdminController@index');

	Route::resource('penilaian', 'Admin\PenilaianController', ['only' => 'index'])->names(['index' => 'adminPenilaian.index']);

	Route::group(['prefix' => 'reviewer'], function () {
		Route::resource('/', 'Admin\ReviewerController', [
			'only' => ['index', 'store']
		])->names([
			'index' => 'adminReviewer.index',
			'store' => 'adminReviewer.store'
		]);
		Route::get('generate-penelitian', 'Admin\ReviewerController@generateReviewerPenelitian')->name('adminReviewer.generatePenelitian');
		Route::get('generate-pengabdian', 'Admin\ReviewerController@generateReviewerPengabdian')->name('adminReviewer.generatePengabdian');
	});

	Route::group(['prefix' => 'skema'], function()
	{
		Route::resource('/', 'Admin\SkemaController', ['only' => 'index'])->names(['index' => 'skema.index']);
		Route::get('/data-penelitian/{id}', 'Admin\AdminController@getskemapenelitian');
		Route::get('/data-pengabdian/{id}', 'Admin\AdminController@getskemapengabdian');
		Route::resource('/penelitian', 'Admin\SkemaPenelitianController', [
			'except' => 'index'
		])->names([
			'create' => 'skemapenelitian.create',
			'store' => 'skemapenelitian.store',
			'show' => 'skemapenelitian.show',
			'edit' => 'skemapenelitian.edit',
			'update' => 'skemapenelitian.update',
			'destroy' => 'skemapenelitian.destroy'
		]);
		Route::resource('/pengabdian', 'Admin\SkemaPengabdianController', [
			'except' => 'index'
		])->names([
			'create' => 'skemapengabdian.create',
			'store' => 'skemapengabdian.store',
			'show' => 'skemapengabdian.show',
			'edit' => 'skemapengabdian.edit',
			'update' => 'skemapengabdian.update',
			'destroy' => 'skemapengabdian.destroy'
		]);
	});

	Route::group(['prefix' => 'user'], function()
	{
		Route::get('/', 'Admin\UserController@index')->name('user.index');
		Route::post('/update-password', 'Admin\UserController@updatepassword')->name('admin.updatepassword');
		Route::post('/update-user', 'Admin\UserController@updateuser')->name('admin.updateuser');
	});

	Route::get('/data-dosen/{id}', 'Admin\AdminController@getDosen');
	Route::resource('/dosen', 'Admin\DosenController');
	Route::get('/reset-password/{id}', 'Admin\UserController@resetPassword')->name('admin.reset_password');
	Route::get('/role-user/{id}', 'Admin\AdminController@getRole');
	Route::group(['prefix' => 'penelitian'], function()
		{
			Route::get('/usulan','Admin\PenelitianController@getAllUsulan');
		}
	);
	Route::group(['prefix' => 'pengabdian'], function()
		{
			Route::get('/usulan','Admin\PengabdianController@getAllUsulan');
		}
	);
	
	Route::get('/data-usulan/penelitian/{id}', 'Admin\AdminController@getUsulanPenelitian');
	Route::get('/data-usulan/pengabdian/{id}', 'Admin\AdminController@getUsulanPengabdian');
	Route::get('/data-penilaian/{id}', 'Admin\PenilaianController@firstPenelitian');
	Route::get('/approver', function() {
    return view('admin.approver');
	});
});

Route::group(['prefix' => 'dosen'], function(){
	// semua url /dosen/.. digroup sini

	Route::get('/','Dosen\DosenController@index');
	Route::resource('/tanggungan', 'Dosen\TanggunganController');
	Route::get('/sinta', 'Dosen\DosenController@sinta')->name('dosen.sinta');
	Route::resource('/usulan', 'Dosen\UsulanController', [
		'only' => ['index', 'create', 'store', 'show', 'update']
	]);
	Route::resource('/pengabdian', 'Dosen\UsulanPengabdianController', [
		'only' => ['index', 'create', 'store', 'show', 'update']
	]);
});

Route::group(['prefix' => 'pimpinan'], function()
{
	// semua url /pimpinan/.. digroup sini

	Route::view('/', 'home.pimpinan');
	Route::get('/approver', function() {
    return view('pimpinan.approver');
	});

	Route::resource('penilaian', 'Admin\PenilaianController', ['only' => 'index'])->names(['index' => 'pimpinanPenilaian.index']);

	Route::group(['prefix' => 'reviewer'], function () {
		Route::resource('/', 'Admin\ReviewerController', [
			'only' => ['index', 'store']
		])->names([
			'index' => 'pimpinanReviewer.index',
			'store' => 'pimpinanReviewer.store'
		]);
		Route::get('generate-penelitian', 'Admin\ReviewerController@generateReviewerPenelitian')->name('pimpinanReviewer.generatePenelitian');
		Route::get('generate-pengabdian', 'Admin\ReviewerController@generateReviewerPengabdian')->name('pimpinanReviewer.generatePengabdian');
	});
});

Route::group(['prefix' => 'penelitian'], function()
{
	// semua url /penelitian/.. digroup sini

	Route::view('/', 'home.penelitian');
	Route::get('/pembagian-reviewer', function() {
    return view('penelitian.pembagian-reviewer');
	});
});

Route::group(['prefix' => 'pengabdian'], function()
{
	// semua url /pengabdian/.. digroup sini

	Route::view('/', 'home.pengabdian');
	Route::get('/pembagian-reviewer', function() {
    return view('pengabdian.pembagian-reviewer');
	});
});

Route::group(['prefix' => 'reviewer'], function()
{
	// semua url /reviewer/.. digroup sini

	Route::get('/', 'Reviewer\ReviewerController@index')->name('reviewerHome.index');
	Route::resource('/review', 'Reviewer\ReviewController', [
		'only' => ['index', 'store']
	])->names([
		'index' => 'reviewerReview.index', 'store' => 'reviewerReview.store'
	]);
	Route::get('/tes', function() {
    return view('reviewer.review');
	});
});

resources/views/layouts/sidebar/admin.blade.php
<!-- Sidebar Menu -->
<nav class="mt-2">
  <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
          with font-awesome or any other icon font library -->
    <li class="nav-item">
      <a href="/" class="nav-link @yield('general-active')">
        <i class="nav-icon fas fa-home"></i>
        <p>
          Beranda
        </p>
      </a>
    </li>
    <li class="nav-item has-treeview @yield('datamaster-open')">
      <a href="#" class="nav-link @yield('datamaster-active')">
        <i class="nav-icon fas fa-database"></i>
        <p>
          Data Master
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{{ route('dosen.index') }}" class="nav-link @yield('dosen-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Dosen</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('user.index') }}" class="nav-link @yield('user-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>User</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('skema.index') }}" class="nav-link @yield('skema-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Skema</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link @yield('prodi-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Prodi</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item has-treeview @yield('reviewer-open')">
      <a href="#" class="nav-link @yield('reviewer-active')">
        <i class="nav-icon fas fa-book"></i>
        <p>
          Review
          <i class="fas fa-angle-left right"></i>
        </p>
      </a> 
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{{ route('adminReviewer.index') }}" class="nav-link @yield('pembagian-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Pembagian Reviewer</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('adminPenilaian.index') }}" class="nav-link @yield('penilaian-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Penilaian</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item has-treeview @yield('pemantauan-open')">
      <a href="#" class="nav-link @yield('pemantauan-active')">
        <i class="nav-icon fas fa-eye"></i>
        <p>
          Monitoring Internal
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{{url('/admin/penelitian/usulan')}}" class="nav-link @yield('list-usulan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>List Usulan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Laporan Kemajuan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Laporan Akhir</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Laporan Belanja</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Publikasi</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item has-treeview @yield('pemantauan-open')">
      <a href="#" class="nav-link @yield('datapendukung-active')">
        <i class="nav-icon fas fa-archive"></i>
        <p>
          Data Pendukung  
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Tambah Usulan</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('approver-active')">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Approver
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('profil-active')">
        <i class="nav-icon fas fa-user"></i>
        <p>
          {{-- Profil Lembaga dan Pimpinan --}}
          Profil Lembaga dan...
        </p>
      </a>
    </li>
  </ul>
</nav>
<!-- /.sidebar-menu -->

resources/views/layouts/sidebar/dosen.blade.php
@section('datamaster-active')
    active
@endsection

@section('dosen-active')
    
@endsection

<!-- Sidebar Menu -->
<nav class="mt-2">
  <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
          with font-awesome or any other icon font library -->
    <li class="nav-item">
      <a href="/" class="nav-link @yield('general-active')">
        <i class="nav-icon fas fa-home"></i>
        <p>
          Dashboard
        </p>
      </a>
    </li>
    <li class="nav-item has-treeview @yield('usulan-open')">
      <a href="#" class="nav-link @yield('usulan-active')">
        <i class="nav-icon fas fa-envelope"></i>
        <p>
          Penelitian
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link @yield('tambahusulan-active')" data-toggle="modal" data-target="#modal-tambahusulan" data-value="#">
            <i class="far fa-circle nav-icon"></i>
            <p>Tambah/Ubah Usulan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('usulan.index') }}" class="nav-link @yield('riwayatusulan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Riwayat Penelitian</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('tanggungan.index') }}" class="nav-link @yield('tanggungan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Tanggungan</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item has-treeview @yield('pengabdian-open')">
      <a href="#" class="nav-link @yield('pengabdian-active')">
        <i class="nav-icon fas fa-envelope"></i>
        <p>
          Pengabdian
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link @yield('tambahusulanpengabdian-active')" data-toggle="modal" data-target="#modal-tambahpengabdian" data-value="#">
            <i class="far fa-circle nav-icon"></i>
            <p>Tambah/Ubah Usulan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('tanggungan.index') }}" class="nav-link @yield('tanggungan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Tanggungan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('pengabdian.index') }}" class="nav-link @yield('riwayatusulan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Riwayat Usulan</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('pelaksanaan-active')">
        <i class="nav-icon fas fa-calendar"></i>
        <p>
          Pelaksanaan
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('menupenelitian-active')">
        <i class="nav-icon fas fa-archive"></i>
        <p>
          Penelitian
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('menupengabdian-active')">
        <i class="nav-icon fas fa-archive"></i>
        <p>
          Pengabdian
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('persetujuanpersonil-active')">
        <i class="nav-icon fas fa-user"></i>
        <p>
          Persetujuan Personil
        </p>
      </a>
    </li>
  </ul>
</nav>
<!-- /.sidebar-menu -->

resources/views/layouts/sidebar/layout.blade.php
<!-- Sidebar -->
<div class="sidebar" style="padding-left: 0%; padding-right: 0%">
    <!-- Sidebar user (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="{{ asset('assets/img/user.png') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a class="d-block">{{ $username->nama }}</a>
            <a class="d-block">{{ $username->nidn }}</a>
        </div>
    </div>
    @include('layouts.sidebar.' . Auth::user()->getActiveRole(Auth::user()->id))
    </div>
<!-- /.sidebar -->

resources/views/layouts/sidebar/modal.blade.php
<div class="modal fade" id="modal-tambahusulan" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Pilih Skema Penelitian</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{ route('usulan.store') }}" method="post">
        @csrf
        <div class="modal-body">
          <input type="hidden" name="step" value="1">
          <input type="hidden" name="id_dosen" value="{{ Auth::user()->username }}">
          <div class="form-group">
            <label for="">NAMA SKEMA</label>
            <select class="form-control @error('skema') is-invalid @enderror tahun-skema" id="skema" name="skema" required autofocus>
              <option value="" hidden>--Pilih Tahun Usulan</option>
              @foreach ($skemaPenelitian as $item)
                <option value="{{ $item->id }}">{{ $item->nama }}</option>
              @endforeach
            </select>

            @error('tahun_usulan')
              <div class="alert alert-danger">{{ $message }}</div>
            @enderror
          </div>
          <div class="form-group">
            <label for="">TAHUN PENELITIAN</label>
            <input class="form-control @error('tahun_penelitian') is-invalid @enderror" type="text" id="tahun_penelitian" name="tahun_penelitian" value="{{ date('Y') }}" required>

            @error('tahun_penelitian')
              <div class="alert alert-danger">{{ $message }}</div>
            @enderror
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
          <button type="submit" class="btn btn-primary">Selanjutnya</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-tambahpengabdian" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Pilih Skema Pengabdian</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{ route('pengabdian.store') }}" method="post">
        @csrf
        <div class="modal-body">
          <input type="hidden" name="step" value="1">
          <input type="hidden" name="id_dosen" value="{{ Auth::user()->username }}">
          <div class="form-group">
            <label for="">NAMA SKEMA</label>
            <select class="form-control @error('skema') is-invalid @enderror tahun-skema" id="skema" name="skema" required autofocus>
              <option value="" hidden>--Pilih Tahun Usulan</option>
              @foreach ($skemaPengabdian as $item)
                <option value="{{ $item->id }}">{{ $item->nama }}</option>
              @endforeach
            </select>

            @error('tahun_usulan')
              <div class="alert alert-danger">{{ $message }}</div>
            @enderror
          </div>
          <div class="form-group">
            <label for="">TAHUN PENGABDIAN</label>
            <input class="form-control @error('tahun_pengabdian') is-invalid @enderror" type="text" id="tahun_pengabdian" name="tahun_pengabdian" value="{{ date('Y') }}" required>

            @error('tahun_pengabdian')
              <div class="alert alert-danger">{{ $message }}</div>
            @enderror
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
          <button type="submit" class="btn btn-primary">Selanjutnya</button>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/layouts/sidebar/penelitian.blade.php
<!-- Sidebar Menu -->
<nav class="mt-2">
  <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
          with font-awesome or any other icon font library -->
    <li class="nav-item">
      <a href="/" class="nav-link @yield('general-active')">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Dashboard
        </p>
      </a>
    </li>
    <li class="nav-item has-treeview @yield('reviewer-open')">
      <a href="#" class="nav-link @yield('reviewer-active')">
        <i class="nav-icon fas fa-book"></i>
        <p>
          Review
          <i class="fas fa-angle-left right"></i>
        </p>
      </a> 
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link @yield('pembagian-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Pembagian Reviewer</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item has-treeview @yield('usulan-open')">
      <a href="#" class="nav-link @yield('usulan-active')">
        <i class="nav-icon fas fa-copy"></i>
        <p>
          Usulan
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link @yield('tambahusulan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Tambah Usulan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link @yield('tanggungan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Tanggungan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link @yield('riwayatusulan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Riwayat Usulan</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('pelaksanaan-active')">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Pelaksanaan
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('persetujuanpersonil-active')">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Persetujuan Personil
        </p>
      </a>
    </li>
  </ul>
</nav>
<!-- /.sidebar-menu -->

resources/views/layouts/sidebar/pengabdian.blade.php
<!-- Sidebar Menu -->
<nav class="mt-2">
  <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
          with font-awesome or any other icon font library -->
    <li class="nav-item">
      <a href="/" class="nav-link @yield('general-active')">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Dashboard
        </p>
      </a>
    </li>
    <li class="nav-item has-treeview @yield('reviewer-open')">
      <a href="#" class="nav-link @yield('reviewer-active')">
        <i class="nav-icon fas fa-book"></i>
        <p>
          Review
          <i class="fas fa-angle-left right"></i>
        </p>
      </a> 
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link @yield('pembagian-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Pembagian Reviewer</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item has-treeview @yield('usulan-open')">
      <a href="#" class="nav-link @yield('usulan-active')">
        <i class="nav-icon fas fa-copy"></i>
        <p>
          Usulan
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link @yield('tambahusulan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Tambah Usulan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link @yield('tanggungan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Tanggungan</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link @yield('riwayatusulan-active')">
            <i class="far fa-circle nav-icon"></i>
            <p>Riwayat Usulan</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('pelaksanaan-active')">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Pelaksanaan
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link @yield('persetujuanpersonil-active')">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Persetujuan Personil
        </p>
      </a>
    </li>
  </ul>
</nav>
<!-- /.sidebar-menu -->