routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

use App\ListRole;
use App\Penelitian;
use App\Pengabdian;
use App\RoleUser;
use App\SkemaPenelitian;
use App\SkemaPengabdian;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Using Closure based composers...
View::composer(['*'], function ($view) {
	if (isset(Auth::user()->id)) {
		$role = RoleUser::select('roles.description as description')
							->join('roles', 'role_user.role_id', 'roles.id')
							->firstWhere('role_user.user_id', Auth::user()->id);

		$roles = ListRole::select('list_roles.role_id as role_id', 'roles.description as description')
							->join('roles', 'list_roles.role_id', 'roles.id')
							->where('list_roles.user_id', Auth::user()->id)
							->get();
							
		$username = User::join('user_data', 'users.username', 'user_data.nidn')
							->select('user_data.nama', 'user_data.nidn')
							->firstWhere('users.id', Auth::user()->id);

		$rolecount = $roles->count();

        $skemaPenelitian = SkemaPenelitian::getSkemaByNIDN(Auth::user()->username);
        $skemaPengabdian = SkemaPengabdian::getSkemaByNIDN(Auth::user()->username);
										
		$view->with('skemaPenelitian', $skemaPenelitian);
		$view->with('skemaPengabdian', $skemaPengabdian);
		$view->with('role', $role);
		$view->with('roles', $roles);
		$view->with('rolecount', $rolecount);
		$view->with('username', $username);
	}
});

Route::get('tes', 'HomeController@test');

Route::get('/install','InstallController@install');
Auth::routes();
//testing upload read doc
Route::get('/doc','HomeController@docTest');
Route::post('/doc','HomeController@docProses');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/author', 'HomeController@author')->name('author');
Route::get('/penelitian/{id}', 'HomeController@firstPenelitian');
Route::get('/pengabdian/{id}', 'HomeController@firstPengabdian');
Route::get('/author', 'HomeController@author')->name('author');

Auth::routes();
Route::resource('/profil', 'ProfilController', [
	'only' => ['index', 'update']
]);
Route::get('/profil/edit', 'ProfilController@edit')->name('profil.edit');
Route::get('/skema/penelitian/{id}', 'HomeController@skemaPenelitian');
Route::get('/skema/pengabdian/{id}', 'HomeController@skemaPengabdian');


/*Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');
*/

Route::get('publications', 'Admin\GoogleScholarController@publications');
Route::get('latest-publication', 'Admin\GoogleScholarController@publication');
Route::get('statistics', 'Admin\GoogleScholarController@statistics');

Route::get('kepala-prodi', 'HomeController@getKepalaProdi')->name('getKepalaProdi');
Route::get('kepala-prodi/{id}', 'HomeController@firstKepalaProdi')->name('firstKepalaProdi');
Route::post('roles', 'HomeController@updateRole')->name('role_update');

Route::group(['prefix' => 'admin'], function()
{
	// semua url /admin/.. digroup sini
	//Route::get('/tes/{nidn}','Admin\PenelitianController@tes');
	Route::get('/', 'Admin\AdminController@index');

	Route::resource('penilaian', 'Admin\PenilaianController', ['only' => 'index'])->names(['index' => 'adminPenilaian.index']);

	Route::group(['prefix' => 'reviewer'], function () {
		Route::resource('/', 'Admin\ReviewerController', [
			'only' => ['index', 'store']
		])->names([
			'index' => 'adminReviewer.index',
			'store' => 'adminReviewer.store'
		]);
		Route::get('generate-penelitian', 'Admin\ReviewerController@generateReviewerPenelitian')->name('adminReviewer.generatePenelitian');
		Route::get('generate-pengabdian', 'Admin\ReviewerController@generateReviewerPengabdian')->name('adminReviewer.generatePengabdian');
	});

	Route::group(['prefix' => 'skema'], function()
	{
		Route::resource('/', 'Admin\SkemaController', ['only' => 'index'])->names(['index' => 'skema.index']);
		Route::get('/data-penelitian/{id}', 'Admin\AdminController@getskemapenelitian');
		Route::get('/data-pengabdian/{id}', 'Admin\AdminController@getskemapengabdian');
		Route::resource('/penelitian', 'Admin\SkemaPenelitianController', [
			'except' => 'index'
		])->names([
			'create' => 'skemapenelitian.create',
			'store' => 'skemapenelitian.store',
			'show' => 'skemapenelitian.show',
			'edit' => 'skemapenelitian.edit',
			'update' => 'skemapenelitian.update',
			'destroy' => 'skemapenelitian.destroy'
		]);
		Route::resource('/pengabdian', 'Admin\SkemaPengabdianController', [
			'except' => 'index'
		])->names([
			'create' => 'skemapengabdian.create',
			'store' => 'skemapengabdian.store',
			'show' => 'skemapengabdian.show',
			'edit' => 'skemapengabdian.edit',
			'update' => 'skemapengabdian.update',
			'destroy' => 'skemapengabdian.destroy'
		]);
	});

	Route::group(['prefix' => 'user'], function()
	{
		Route::get('/', 'Admin\UserController@index')->name('user.index');
		Route::post('/update-password', 'Admin\UserController@updatepassword')->name('admin.updatepassword');
		Route::post('/update-user', 'Admin\UserController@updateuser')->name('admin.updateuser');
	});

	Route::get('/data-dosen/{id}', 'Admin\AdminController@getDosen');
	Route::resource('/dosen', 'Admin\DosenController');
	Route::get('/reset-password/{id}', 'Admin\UserController@resetPassword')->name('admin.reset_password');
	Route::get('/role-user/{id}', 'Admin\AdminController@getRole');
	Route::group(['prefix' => 'penelitian'], function()
		{
			Route::get('/usulan','Admin\PenelitianController@getAllUsulan');
		}
	);
	Route::group(['prefix' => 'pengabdian'], function()
		{
			Route::get('/usulan','Admin\PengabdianController@getAllUsulan');
		}
	);
	
	Route::get('/data-usulan/penelitian/{id}', 'Admin\AdminController@getUsulanPenelitian');
	Route::get('/data-usulan/pengabdian/{id}', 'Admin\AdminController@getUsulanPengabdian');
	Route::get('/data-penilaian/{id}', 'Admin\PenilaianController@firstPenelitian');
	Route::get('/approver', function() {
    return view('admin.approver');
	});
});

Route::group(['prefix' => 'dosen'], function(){
	// semua url /dosen/.. digroup sini

	Route::get('/','Dosen\DosenController@index');
	Route::resource('/tanggungan', 'Dosen\TanggunganController');
	Route::get('/sinta', 'Dosen\DosenController@sinta')->name('dosen.sinta');
	Route::resource('/usulan', 'Dosen\UsulanController', [
		'only' => ['index', 'create', 'store', 'show', 'update']
	]);
	Route::resource('/pengabdian', 'Dosen\UsulanPengabdianController', [
		'only' => ['index', 'create', 'store', 'show', 'update']
	]);
});

Route::group(['prefix' => 'pimpinan'], function()
{
	// semua url /pimpinan/.. digroup sini

	Route::view('/', 'home.pimpinan');
	Route::get('/approver', function() {
    return view('pimpinan.approver');
	});

	Route::resource('penilaian', 'Admin\PenilaianController', ['only' => 'index'])->names(['index' => 'pimpinanPenilaian.index']);

	Route::group(['prefix' => 'reviewer'], function () {
		Route::resource('/', 'Admin\ReviewerController', [
			'only' => ['index', 'store']
		])->names([
			'index' => 'pimpinanReviewer.index',
			'store' => 'pimpinanReviewer.store'
		]);
		Route::get('generate-penelitian', 'Admin\ReviewerController@generateReviewerPenelitian')->name('pimpinanReviewer.generatePenelitian');
		Route::get('generate-pengabdian', 'Admin\ReviewerController@generateReviewerPengabdian')->name('pimpinanReviewer.generatePengabdian');
	});
});

Route::group(['prefix' => 'penelitian'], function()
{
	// semua url /penelitian/.. digroup sini

	Route::view('/', 'home.penelitian');
	Route::get('/pembagian-reviewer', function() {
    return view('penelitian.pembagian-reviewer');
	});
});

Route::group(['prefix' => 'pengabdian'], function()
{
	// semua url /pengabdian/.. digroup sini

	Route::view('/', 'home.pengabdian');
	Route::get('/pembagian-reviewer', function() {
    return view('pengabdian.pembagian-reviewer');
	});
});

Route::group(['prefix' => 'reviewer'], function()
{
	// semua url /reviewer/.. digroup sini

	Route::get('/', 'Reviewer\ReviewerController@index')->name('reviewerHome.index');
	Route::resource('/review', 'Reviewer\ReviewController', [
		'only' => ['index', 'store']
	])->names([
		'index' => 'reviewerReview.index', 'store' => 'reviewerReview.store'
	]);
	Route::get('/tes', function() {
    return view('reviewer.review');
	});
});

app/Http/Controllers/Admin/DosenController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Dosen;
use App\Role;
use App\ListRole;
use App\User;
use App\UserRole;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use App\JabatanAkademik;

class DosenController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Untuk mengambil Data Role sesuai User
        $dosen = Dosen::all();

        return view('admin.dosen', compact('dosen'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jabatan_akademik = JabatanAkademik::get();

        return view('admin.dosen-create', compact('jabatan_akademik'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nidn' => 'numeric',
            'nama' => 'required',
            'alamat' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required|date',
            'ktp' => 'required|numeric',
            'telepon' => 'required|numeric',
            'hp' => 'required|numeric',
            'email' => 'required|email',
            'website_personal' => 'required',
            'jabatan_fungsional' => 'required',
            'sinta_id' => 'required',
            'google_scholar' => 'required'
        ]);
        
        $ceknidn = Dosen::where('nidn', $request->get('nidn'))->first();
        if (isset($ceknidn->nidn)) {
            return back()->with('error', 'Data dosen telah terdaftar');
        } else {
            $nidn = $request->get('nidn');
            $nama = $request->get('nama');
            $alamat = $request->get('alamat');
            $tempat_lahir = $request->get('tempat_lahir');
            $tanggal_lahir = $request->get('tanggal_lahir');
            $ktp = $request->get('ktp');
            $telepon = $request->get('telepon');
            $hp = $request->get('hp');
            $email = $request->get('email');
            $website_personal = $request->get('website_personal');
            $jabatan_fungsional = $request->get('jabatan_fungsional');
            $sinta_id = $request->get('sinta_id');
            $google_scholar = $request->get('google_scholar');
            $status = 1;
            
            if ($request->get('status') == null) {
                $status = 2;
            }
    
            $user_data = Dosen::storeDosen($nidn, $nama, $alamat, $tempat_lahir, $tanggal_lahir, $ktp, $telepon, $hp, $email, $website_personal, $jabatan_fungsional, $sinta_id, $google_scholar, $status);
            $user = User::storeUser($nidn);
            $list_role = ListRole::storeListRole();
    
            return redirect()->route('dosen.index')->with('success', 'Data dosen telah ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dosen = Dosen::findOrFail($id);
        $jabatan_akademik = JabatanAkademik::get();

        return view('admin.dosen-edit', compact('dosen', 'jabatan_akademik'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function importExcel()
    {
        $this->validate($request, [
            'select_file'   => 'required|mimes:xls,xlsx'
        ]);
        
        Excel::import(new DosenImport, request()->file('select_file'));

        return redirect('/')->with('success', 'Data dosen berhasil ditambahkan');
    }
}

app/Http/Controllers/Dosen/DosenController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\ListRole;
use App\Dosen;

class DosenController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:dosen');
    }

    public function index()
    {
        $dosen = Dosen::findOrFail(Auth::user()->id);
        return view('home.dosen', compact('dosen'));
    }
    
    public function sinta()
    {
        $dosen = Dosen::findOrFail(Auth::user()->id);
        return view('dosen.sinta', compact('dosen'));
    }
}

app/Http/Controllers/Dosen/SintaController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SintaController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:dosen');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dosen.sinta');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dosen/TanggunganController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TanggunganController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:dosen');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dosen.tanggungan');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dosen/usulan/form1.blade.php
<form role="form" method="POST" action="{{ route('usulan.store') }}">
  @csrf
  <div class="card-body">
    <input type="hidden" name="step" value="1">
    <input type="hidden" name="id_dosen" value="{{ Auth::user()->username }}">
    <div class="form-group">
      <label for="">NAMA SKEMA</label>
      <select class="form-control @error('skema') is-invalid @enderror tahun-skema" id="skema" name="skema" required autofocus>
        <option value="" hidden>--Pilih Tahun Usulan</option>
        @foreach ($skemaPenelitian as $item)
          <option value="{{ $item->id }}">{{ $item->nama }}</option>
        @endforeach
      </select>

      @error('tahun_usulan')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
    </div>
    <div class="form-group">
      <label for="">TAHUN PENELITIAN</label>
      <input class="form-control @error('tahun_penelitian') is-invalid @enderror" type="text" id="tahun_penelitian" name="tahun_penelitian" value="{{ date('Y') }}" required>

      @error('tahun_penelitian')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
    </div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <div class="card-tools">
      <button type="submit" class="btn btn-primary float-right">Selanjutnya</button>
    </div>
  </div>
</form>

resources/views/dosen/usulan/form3.blade.php
<form role="form" method="POST" action="{{ route('usulan.store') }}">
  @csrf
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    <input type="hidden" name="step" value="3">
    <input type="hidden" name="id_dosen" value="{{ Auth::user()->username }}">
    <input type="hidden" name="id_penelitian" value="{{ $penelitian->id }}">
    @if ($message = Session::get('skema'))
      <input type="hidden" name="skema" value="{{ $message }}">
    @endif
    <div class="form-group">
      <label for="">KETUA</label>
      <input class="form-control" type="text" id="dosen" name="dosen[]" value="{{ $profil->nama }}" disabled>
    </div>
    <div class="form-group" id="select-anggota">
      <label for="">ANGGOTA</label>
      <select class="form-control select1" id="select1" name="dosen[]" autofocus>
        <option value="" hidden>--Pilih dosen</option>
        @foreach ($dosen as $item)
          <option value="{{$item->nidn}}"
            @if (isset($penelitian))
              @if ($item->nama == $penelitian->tahun_usulan)
                  selected
              @endif
            @endif
          >{{$item->nama}}</option>
        @endforeach
      </select>
    </div>
    <button type="button" class="btn btn-success" id="tambah-anggota">Tambah</button>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <div class="card-tools">
      <button type="submit" class="btn btn-primary float-right">Selanjutnya</button>
    </form>
      <form action="{{ route('usulan.update', Auth::user()->username) }}" method="post">
        @csrf
        @method('PATCH')
        @if ($message = Session::get('skema'))
          <input type="hidden" name="skema" value="{{ $message }}">
        @endif
        <button type="submit" class="btn btn-danger float-right mr-2">Kembali</button>
      </form>
    </div>
  </div>
@section('js')
  <!-- Select2 -->
  <script src="{{ asset('/vendor/select2/js/select2.full.min.js') }}"></script>
  <!-- Page script -->
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('#select1').select2({
        theme: 'bootstrap4'
      })
      
      var i = 2;
      //Initialize Select2 Elements
      // $('.select2bs4').select2({
      //   theme: 'bootstrap4'
      // })

      $('#tambah-anggota').on('click', function(e){
        e.preventDefault();
        var teks = `<label for="" class="mt-1">ANGGOTA</label><select class="form-control select" id="select`+i+`" name="dosen[]" autofocus>
                    <option value="" hidden>--Pilih dosen</option>
                    @foreach ($dosen as $item)
                      <option value="{{$item->nidn}}"
                        @if (isset($penelitian))
                          @if ($item->nama == $penelitian->tahun_usulan)
                              selected
                          @endif
                        @endif
                      >{{$item->nama}}</option>
                    @endforeach
                  </select>`;
        $('#select-anggota').append(teks);
        $('#select'+i).select2({
          theme: 'bootstrap4'
        })
        i++;
      })      
    })
  </script>
@endsection

resources/views/dosen/usulan/form4.blade.php
<form role="form" method="POST" action="{{ route('usulan.store') }}">
  @csrf
  <div class="card-body">
    <input type="hidden" name="step" value="4">
    <input type="hidden" name="id_dosen" value="{{ Auth::user()->username }}">
    <input type="hidden" name="id_penelitian" value="{{ $penelitian->id }}">
    <input type="hidden" name="skema" value="{{ $penelitian->skema }}">
    @if ($message = Session::get('skema'))
      <input type="hidden" name="skema" value="{{ $message }}">
    @endif
    <div class="form-group">
      <label for="usulan_dana">USULAN DANA</label>
      <input class="form-control @error('usulan_dana') is-invalid @enderror" type="number" id="usulan_dana" name="usulan_dana"
      @if (isset($penelitian['dana']))  
        value="{{ $penelitian['dana']->usulan_dana }}"
      @endif
      required autofocus>

      @error('usulan_dana')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
    </div>
    <div class="form-group">
      <label for="sumber_dana_lain">SUMBER DANA LAIN</label>
      <input class="form-control @error('sumber_dana_lain') is-invalid @enderror" type="number" id="sumber_dana_lain" name="sumber_dana_lain"
      @if (isset($penelitian['dana']))  
        value="{{ $penelitian['dana']->sumber_dana_lain }}"
      @endif
      required>

      @error('sumber_dana_lain')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
    </div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <div class="card-tools">
      <button type="submit" class="btn btn-primary float-right">Selanjutnya</button>
    </form>
      <form action="{{ route('usulan.update', Auth::user()->username) }}" method="post">
        @csrf
        @method('PATCH')
        @if ($message = Session::get('skema'))
          <input type="hidden" name="skema" value="{{ $message }}">
        @endif
        <button type="submit" class="btn btn-danger float-right mr-2">Kembali</button>
      </form>
    </div>
  </div>

resources/views/dosen/usulan/form5.blade.php
<form role="form" method="POST" action="{{ route('usulan.store') }}">
  @csrf
  <div class="card-body">
    <input type="hidden" name="step" value="5">
    <input type="hidden" name="id_dosen" value="{{ Auth::user()->username }}">
    <input type="hidden" name="id_penelitian" value="{{ $penelitian->id }}">
    <input type="hidden" name="skema" value="{{ $penelitian->skema }}">
    @if ($message = Session::get('skema'))
      <input type="hidden" name="skema" value="{{ $message }}">
    @endif
    <div class="form-group">
      <label for="">PROGRAM STUDI</label>
      <select class="form-control @error('program_studi') is-invalid @enderror program-studi" id="program_studi" name="program_studi" required autofocus>
        <option value="" hidden>--Pilih Program Studi</option>
        @foreach ($program_studi as $item)
          <option value={{$item->id}}
            @if (isset($penelitian))
              @if ($item->id == $penelitian->program_studi)
                  selected="selected"
              @endif
            @endif  
          >{{$item->nama}}</option>  
        @endforeach
      </select>

      @error('program_studi')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
    </div>
    <div class="form-group">
      <label for="">KEPALA PROGRAM STUDI</label>
      <input class="form-control" type="text" id="kaprodi" name="kaprodi" value="" hidden>
      <input class="form-control" type="text" id="kaprodi2" name="" value="" disabled>
    </div>
    <div class="form-group">
      <label for="">KEPALA LPPM</label>
      <input class="form-control" type="text" id="kalppm" name="kalppm" value="{{ $kepala_lppm->nidn }}" hidden>
      <input class="form-control" type="text" id="" name="" value="{{ $kepala_lppm->nama }}" disabled>
    </div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <div class="card-tools">
      <button type="submit" class="btn btn-primary float-right">Selanjutnya</button>
    </form>
      <form action="{{ route('usulan.update', Auth::user()->username) }}" method="post">
        @csrf
        @method('PATCH')
        @if ($message = Session::get('skema'))
          <input type="hidden" name="skema" value="{{ $message }}">
        @endif
        <button type="submit" class="btn btn-danger float-right mr-2">Kembali</button>
      </form>
    </div>
  </div>