routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

use App\ListRole;
use App\Penelitian;
use App\Pengabdian;
use App\RoleUser;
use App\SkemaPenelitian;
use App\SkemaPengabdian;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Using Closure based composers...
View::composer(['*'], function ($view) {
	if (isset(Auth::user()->id)) {
		$role = RoleUser::select('roles.description as description')
							->join('roles', 'role_user.role_id', 'roles.id')
							->firstWhere('role_user.user_id', Auth::user()->id);

		$roles = ListRole::select('list_roles.role_id as role_id', 'roles.description as description')
							->join('roles', 'list_roles.role_id', 'roles.id')
							->where('list_roles.user_id', Auth::user()->id)
							->get();
							
		$username = User::join('user_data', 'users.username', 'user_data.nidn')
							->select('user_data.nama', 'user_data.nidn')
							->firstWhere('users.id', Auth::user()->id);

		$rolecount = $roles->count();

        $skemaPenelitian = SkemaPenelitian::getSkemaByNIDN(Auth::user()->username);
        $skemaPengabdian = SkemaPengabdian::getSkemaByNIDN(Auth::user()->username);
										
		$view->with('skemaPenelitian', $skemaPenelitian);
		$view->with('skemaPengabdian', $skemaPengabdian);
		$view->with('role', $role);
		$view->with('roles', $roles);
		$view->with('rolecount', $rolecount);
		$view->with('username', $username);
	}
});

Route::get('tes', 'HomeController@test');

Route::get('/install','InstallController@install');
Auth::routes();
//testing upload read doc
Route::get('/doc','HomeController@docTest');
Route::post('/doc','HomeController@docProses');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/author', 'HomeController@author')->name('author');
Route::get('/penelitian/{id}', 'HomeController@firstPenelitian');
Route::get('/pengabdian/{id}', 'HomeController@firstPengabdian');
Route::get('/author', 'HomeController@author')->name('author');

Auth::routes();
Route::resource('/profil', 'ProfilController', [
	'only' => ['index', 'update']
]);
Route::get('/profil/edit', 'ProfilController@edit')->name('profil.edit');
Route::get('/skema/penelitian/{id}', 'HomeController@skemaPenelitian');
Route::get('/skema/pengabdian/{id}', 'HomeController@skemaPengabdian');


/*Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');
*/

Route::get('publications', 'Admin\GoogleScholarController@publications');
Route::get('latest-publication', 'Admin\GoogleScholarController@publication');
Route::get('statistics', 'Admin\GoogleScholarController@statistics');

Route::get('kepala-prodi', 'HomeController@getKepalaProdi')->name('getKepalaProdi');
Route::get('kepala-prodi/{id}', 'HomeController@firstKepalaProdi')->name('firstKepalaProdi');
Route::post('roles', 'HomeController@updateRole')->name('role_update');

Route::group(['prefix' => 'admin'], function()
{
	// semua url /admin/.. digroup sini
	//Route::get('/tes/{nidn}','Admin\PenelitianController@tes');
	Route::get('/', 'Admin\AdminController@index');

	Route::resource('penilaian', 'Admin\PenilaianController', ['only' => 'index'])->names(['index' => 'adminPenilaian.index']);

	Route::group(['prefix' => 'reviewer'], function () {
		Route::resource('/', 'Admin\ReviewerController', [
			'only' => ['index', 'store']
		])->names([
			'index' => 'adminReviewer.index',
			'store' => 'adminReviewer.store'
		]);
		Route::get('generate-penelitian', 'Admin\ReviewerController@generateReviewerPenelitian')->name('adminReviewer.generatePenelitian');
		Route::get('generate-pengabdian', 'Admin\ReviewerController@generateReviewerPengabdian')->name('adminReviewer.generatePengabdian');
	});

	Route::group(['prefix' => 'skema'], function()
	{
		Route::resource('/', 'Admin\SkemaController', ['only' => 'index'])->names(['index' => 'skema.index']);
		Route::get('/data-penelitian/{id}', 'Admin\AdminController@getskemapenelitian');
		Route::get('/data-pengabdian/{id}', 'Admin\AdminController@getskemapengabdian');
		Route::resource('/penelitian', 'Admin\SkemaPenelitianController', [
			'except' => 'index'
		])->names([
			'create' => 'skemapenelitian.create',
			'store' => 'skemapenelitian.store',
			'show' => 'skemapenelitian.show',
			'edit' => 'skemapenelitian.edit',
			'update' => 'skemapenelitian.update',
			'destroy' => 'skemapenelitian.destroy'
		]);
		Route::resource('/pengabdian', 'Admin\SkemaPengabdianController', [
			'except' => 'index'
		])->names([
			'create' => 'skemapengabdian.create',
			'store' => 'skemapengabdian.store',
			'show' => 'skemapengabdian.show',
			'edit' => 'skemapengabdian.edit',
			'update' => 'skemapengabdian.update',
			'destroy' => 'skemapengabdian.destroy'
		]);
	});

	Route::group(['prefix' => 'user'], function()
	{
		Route::get('/', 'Admin\UserController@index')->name('user.index');
		Route::post('/update-password', 'Admin\UserController@updatepassword')->name('admin.updatepassword');
		Route::post('/update-user', 'Admin\UserController@updateuser')->name('admin.updateuser');
	});

	Route::get('/data-dosen/{id}', 'Admin\AdminController@getDosen');
	Route::resource('/dosen', 'Admin\DosenController');
	Route::get('/reset-password/{id}', 'Admin\UserController@resetPassword')->name('admin.reset_password');
	Route::get('/role-user/{id}', 'Admin\AdminController@getRole');
	Route::group(['prefix' => 'penelitian'], function()
		{
			Route::get('/usulan','Admin\PenelitianController@getAllUsulan');
		}
	);
	Route::group(['prefix' => 'pengabdian'], function()
		{
			Route::get('/usulan','Admin\PengabdianController@getAllUsulan');
		}
	);
	
	Route::get('/data-usulan/penelitian/{id}', 'Admin\AdminController@getUsulanPenelitian');
	Route::get('/data-usulan/pengabdian/{id}', 'Admin\AdminController@getUsulanPengabdian');
	Route::get('/data-penilaian/{id}', 'Admin\PenilaianController@firstPenelitian');
	Route::get('/approver', function() {
    return view('admin.approver');
	});
});

Route::group(['prefix' => 'dosen'], function(){
	// semua url /dosen/.. digroup sini

	Route::get('/','Dosen\DosenController@index');
	Route::resource('/tanggungan', 'Dosen\TanggunganController');
	Route::get('/sinta', 'Dosen\DosenController@sinta')->name('dosen.sinta');
	Route::resource('/usulan', 'Dosen\UsulanController', [
		'only' => ['index', 'create', 'store', 'show', 'update']
	]);
	Route::resource('/pengabdian', 'Dosen\UsulanPengabdianController', [
		'only' => ['index', 'create', 'store', 'show', 'update']
	]);
});

Route::group(['prefix' => 'pimpinan'], function()
{
	// semua url /pimpinan/.. digroup sini

	Route::view('/', 'home.pimpinan');
	Route::get('/approver', function() {
    return view('pimpinan.approver');
	});

	Route::resource('penilaian', 'Admin\PenilaianController', ['only' => 'index'])->names(['index' => 'pimpinanPenilaian.index']);

	Route::group(['prefix' => 'reviewer'], function () {
		Route::resource('/', 'Admin\ReviewerController', [
			'only' => ['index', 'store']
		])->names([
			'index' => 'pimpinanReviewer.index',
			'store' => 'pimpinanReviewer.store'
		]);
		Route::get('generate-penelitian', 'Admin\ReviewerController@generateReviewerPenelitian')->name('pimpinanReviewer.generatePenelitian');
		Route::get('generate-pengabdian', 'Admin\ReviewerController@generateReviewerPengabdian')->name('pimpinanReviewer.generatePengabdian');
	});
});

Route::group(['prefix' => 'penelitian'], function()
{
	// semua url /penelitian/.. digroup sini

	Route::view('/', 'home.penelitian');
	Route::get('/pembagian-reviewer', function() {
    return view('penelitian.pembagian-reviewer');
	});
});

Route::group(['prefix' => 'pengabdian'], function()
{
	// semua url /pengabdian/.. digroup sini

	Route::view('/', 'home.pengabdian');
	Route::get('/pembagian-reviewer', function() {
    return view('pengabdian.pembagian-reviewer');
	});
});

Route::group(['prefix' => 'reviewer'], function()
{
	// semua url /reviewer/.. digroup sini

	Route::get('/', 'Reviewer\ReviewerController@index')->name('reviewerHome.index');
	Route::resource('/review', 'Reviewer\ReviewController', [
		'only' => ['index', 'store']
	])->names([
		'index' => 'reviewerReview.index', 'store' => 'reviewerReview.store'
	]);
	Route::get('/tes', function() {
    return view('reviewer.review');
	});
});

resources/views/admin/dosen-create.blade.php
@extends('adminlte::page')

@section('datamaster-open')
    menu-open
@endsection

@section('datamaster-active')
    active
@endsection

@section('dosen-active')
    active
@endsection

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Tambah Data Dosen</h1>
@stop

@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/fontawesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">
@endsection

@section('content')
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Tambah Data Dosen</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{{ route('dosen.store') }}">
              @csrf
              <div class="card-body">
                @if ($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                          <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                  </div><br />
                @endif
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="nidn">NIDN</label>
                      <input type="number" class="form-control" id="nidn" name="nidn" placeholder="Masukkan NIDN" value="{{ old('nidn') }}" required>
                      @error('nidn')
                        <div class="invalid-feedback d-block">{{ $message }}</div>
                      @enderror
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="nama">Nama</label>
                      <input type="text" class="form-control" id="nama" name="nama" placeholder="Masukkan Nama" value="{{ old('nama') }}" required>
                      @error('nama')
                        <div class="invalid-feedback d-block">{{ $message }}</div>
                      @enderror
                    </div>
                  </div>
                  <div class="col-md-6">
                    <!-- textarea -->
                    <div class="form-group">
                      <label>Alamat</label>
                      <textarea class="form-control" rows="4" name="alamat" placeholder="Masukkan Alamat">{{ old('alamat') }}</textarea>
                      @error('alamat')
                        <div class="invalid-feedback d-block">{{ $message }}</div>
                      @enderror
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="tempatlahir">Tempat Lahir</label>
                      <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="Masukkan Tempat Lahir" value="{{ old('tempat_lahir') }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="tanggal_lahir">Tanggal Lahir</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="far fa-calendar-alt"></i>
                          </span>
                        </div>
                        <input type="date" class="form-control" id="tanggal_lahir" name="tanggal_lahir" placeholder="Masukkan Tempat Lahir" value="{{ old('tanggal_lahir') }}">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">                    
                    <div class="form-group">
                      <label>Jabatan Fungsional</label>
                      <select class="form-control" id="jabatan_fungsional" name="jabatan_fungsional" required>
                        <option value="" hidden>--Pilih Jabatan Fungsional</option>
                        @foreach ($jabatan_akademik as $item)
                            <option value="{{$item->id}}">{{$item->nama}}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="ktp">No. KTP</label>
                      <input type="number" class="form-control" id="ktp" name="ktp" placeholder="Masukkan No. NIK KTP" value="{{ old('ktp') }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="telepon">No. Telepon</label>
                      <input type="number" class="form-control" id="telepon" name="telepon" placeholder="Masukkan No. Telepon" value="{{ old('telepon') }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="hp">No. HP</label>
                      <input type="number" class="form-control" id="hp" name="hp" placeholder="Masukkan No. HP" value="{{ old('hp') }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="email">Email</label>
                      <input type="email" class="form-control" id="email" name="email" placeholder="Masukkan Email" value="{{ old('email') }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="website_personal">Alamat Website Pribadi</label>
                      <input type="text" class="form-control" id="website_personal" name="website_personal" placeholder="Masukkan Alamat Website Pribadi" value="{{ old('website_personal') }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="sinta_id">ID Sinta</label>
                      <input type="text" class="form-control" id="sinta_id" name="sinta_id" placeholder="Masukkan ID Sinta" value="{{ old('sinta_id') }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="google_scholar">ID Google Scholar</label>
                      <input type="text" class="form-control" id="google_scholar" name="google_scholar" placeholder="Masukkan ID Google Scholar" value="{{ old('google_scholar') }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-check">
                      <input type="checkbox" class="form-check-input" id="status" name="status" value="1" checked>
                      <label class="form-check-label font-weight-bold" for="status">Daftar Sebagai Dosen</label>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
        </div>
        <!--/.col (left) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@stop

@section('js')
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('vendor/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
@endsection

resources/views/admin/dosen-edit.blade.php
@extends('adminlte::page')

@section('datamaster-open')
    menu-open
@endsection

@section('datamaster-active')
    active
@endsection

@section('dosen-active')
    active
@endsection

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Ubah Data Dosen</h1>
@stop

@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/fontawesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">
@endsection

@section('content')
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Ubah Data Dosen</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{{ route('dosen.update', $dosen->id) }}">
              @csrf
              <div class="card-body">
                @if ($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                          <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                  </div><br />
                @endif
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="nidn">NIDN</label>
                      <input type="number" class="form-control" id="nidn" name="nidn" placeholder="Masukkan NIDN" value="{{ $dosen->nidn }}" required>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="nama">Nama</label>
                      <input type="text" class="form-control" id="nama" name="nama" placeholder="Masukkan Nama" value="{{ $dosen->nama }}" required>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <!-- textarea -->
                    <div class="form-group">
                      <label>Alamat</label>
                      <textarea class="form-control" rows="4" name="alamat" placeholder="Masukkan Alamat">{{ $dosen->alamat }}</textarea>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="tempatlahir">Tempat Lahir</label>
                      <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="Masukkan Tempat Lahir" value="{{ $dosen->tempat_lahir }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="tanggal_lahir">Tanggal Lahir</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="far fa-calendar-alt"></i>
                          </span>
                        </div>
                        <input type="date" class="form-control" id="tanggal_lahir" name="tanggal_lahir" placeholder="Masukkan Tempat Lahir" value="{{ $dosen->tanggal_lahir }}">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Jabatan Fungsional</label>
                      <select class="form-control" id="jabatan_fungsional" name="jabatan_fungsional" required>
                        @foreach ($jabatan_akademik as $item)
                            <option value="{{$item->id}}">{{$item->nama}}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="ktp">No. KTP</label>
                      <input type="number" class="form-control" id="ktp" name="ktp" placeholder="Masukkan No. NIK KTP" value="{{ $dosen->ktp }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="telepon">No. Telepon</label>
                      <input type="number" class="form-control" id="telepon" name="telepon" placeholder="Masukkan No. Telepon" value="{{ $dosen->telepon }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="hp">No. HP</label>
                      <input type="number" class="form-control" id="hp" name="hp" placeholder="Masukkan No. HP" value="{{ $dosen->hp }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="email">Email</label>
                      <input type="email" class="form-control" id="email" name="email" placeholder="Masukkan Email" value="{{ $dosen->email }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="website_personal">Alamat Website Pribadi</label>
                      <input type="text" class="form-control" id="website_personal" name="website_personal" placeholder="Masukkan Alamat Website Pribadi" value="{{ $dosen->website_personal }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="sinta_id">ID Sinta</label>
                      <input type="text" class="form-control" id="sinta_id" name="sinta_id" placeholder="Masukkan ID Sinta" value="{{ $dosen->sinta_id }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="google_scholar">ID Google Scholar</label>
                      <input type="text" class="form-control" id="google_scholar" name="google_scholar" placeholder="Masukkan ID Google Scholar" value="{{ $dosen->google_scholar }}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-check">
                      <input type="checkbox" class="form-check-input" id="status" name="status" value="1" checked>
                      <label class="form-check-label font-weight-bold" for="status">Daftar Sebagai Dosen</label>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
        </div>
        <!--/.col (left) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@stop

@section('js')
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('vendor/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
@endsection

resources/views/admin/dosen.blade.php
@extends('adminlte::page')

@section('datamaster-open')
    menu-open
@endsection

@section('datamaster-active')
    active
@endsection

@section('dosen-active')
    active
@endsection

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Master Data Dosen</h1>
@stop

@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/fontawesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

@endsection

@section('content')
  <!-- Main content -->
  
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">List Data Dosen</h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
              <div class="container">
                @if(session()->get('success'))
                  <div class="alert alert-success">
                    {{ session()->get('success') }}  
                  </div><br />
                @endif
                <table class="table" id="list-dosen">
                  <thead>
                    <tr>
                      <th>NIDN</th>
                      <th>Nama</th>
                      <th>Aksi</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($dosen as $i)
                      <tr>
                        <td>{{$i->nidn}}</td>
                        <td>{{$i->nama}}</td>
                        <td>
                          <form action="{{ route('dosen.destroy', $i->id) }}" method="POST">
                          <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#modal-default" data-value="{{$i->id}}">Detail</button>
                          <a href="{{ route('dosen.edit', $i->id) }}" class="btn btn-sm btn-primary">Ubah Data</a>
                          @csrf
                            <button type="submit" class="btn btn-sm btn-danger">Hapus Dosen</button>
                          </form>
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
            <!-- /.card-body -->
            
            <div class="card-footer">
              <a href="{{ route('dosen.create') }}" class="btn btn-sm btn-primary"><i class="fas fa-plus"></i> Tambah Dosen</a>
            </div>
            <!-- /.card-footer -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->

    <div class="modal fade" id="modal-default">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Detail Dosen</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <table class="table">
              <tbody>
                <tr>
                  <td>
                    NIDN
                  </td>
                  <td id="modal-nidn">
                    
                  </td>
                </tr>
                <tr>
                  <td>
                    Nama
                  </td>
                  <td id="modal-nama">
                    
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            {{-- <a href="{{ route('dosen.edit', $i->id) }}" class="btn btn-sm btn-primary">Ubah Data</button> --}}
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
  </section>
  <!-- /.content -->
@stop

@section('js')
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('vendor/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript">
    $(document).ready( function () {
      $('#list-dosen').DataTable();
      $( "#list-dosen tbody tr td button" ).on( "click", function() {
        var id = $(this).attr('data-value');
        $.get( "/admin/data-dosen/" + id, function( data ) {
          console.log(JSON.parse(data));
          var d = JSON.parse(data);
          $('#modal-nidn').text(d[0].nidn);
          $('#modal-nama').text(d[0].nama);
        });
        // console.log($(this).attr('data-value'));
      });
      
  } );
  </script>
@endsection